name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.3
            gemfile: Gemfile
          - ruby: 3.3
            gemfile: gemfiles/activerecord71.gemfile
          - ruby: 3.2
            gemfile: gemfiles/activerecord70.gemfile
          - ruby: 3.2
            gemfile: gemfiles/activerecord61.gemfile
          - ruby: 3.1
            gemfile: gemfiles/activerecord61.gemfile
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: ankane/setup-postgres@v1
        with:
          database: neighbor_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.7.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: bundle exec rake test
